# Generated by Django 4.0.3 on 2022-04-12 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goji', '0008_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 12, 18, 49, 11, 268024)),
        ),
    ]
