# Generated by Django 4.0.3 on 2022-04-25 07:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goji', '0010_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_pass',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 13, 33, 27, 77045)),
        ),
    ]
